name: Auto approve

on:
  pull_request:
    types: [opened, edited]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - name: Auto approve if title contains "chore" or "docs" or "revert" or "test"
        if: contains(github.event.pull_request.title, 'chore') ||
          contains(github.event.pull_request.title, 'docs') ||
          contains(github.event.pull_request.title, 'revert') ||
          contains(github.event.pull_request.title, 'test')
        uses: hmarr/auto-approve-action@v4
