name: Auto approve

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Auto approve
        uses: hmarr/auto-approve-action@v4
