name: Auto approve

on:
  pull_request:
    types: [opened, edited]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Auto approve if title starts with "chore:", "docs:", "revert:" or "test:"
        if: startsWith(github.event.pull_request.title, 'chore:') ||
          startsWith(github.event.pull_request.title, 'docs:') ||
          startsWith(github.event.pull_request.title, 'revert:') ||
          startsWith(github.event.pull_request.title, 'test:')
        uses: hmarr/auto-approve-action@f0939ea97e9205ef24d872e76833fa908a770363 # v4.0.0
